### ISSUE TITLE
Test target horks

### ISSUE THREAD

**Issue by doug-wade** [redfin/stratocacher#3]
```
dougwade code/stratocacher ‹master*› » npm i                                                                                                                                  1 ↵
lerna@1.1.1 node_modules/lerna
├── pad@1.0.0
├── progress@1.1.8
├── async@1.5.2
├── semver@5.1.0
├── readline-sync@1.4.2
├── signal-exit@2.1.2
├── mkdirp@0.5.1 (minimist@0.0.8)
├── lodash.unionwith@4.4.0 (lodash._baseflatten@4.2.1, lodash.rest@4.0.3, lodash._baseuniq@4.6.0)
├── rimraf@2.5.2 (glob@7.0.3)
└── chalk@1.1.3 (ansi-styles@2.2.1, escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
dougwade code/stratocacher ‹master*› » lerna bootstrap
Lerna v2.0.0-beta.5
Linking all dependencies
Version mismatch inside "stratocacher-layer-simple-object". Depends on "stratocacher@0.0.8" instead of "stratocacher@^0.0.4".
Version mismatch inside "stratocacher-layer-localstorage". Depends on "stratocacher@0.0.8" instead of "stratocacher@^0.0.4".
Version mismatch inside "stratocacher-layer-lru". Depends on "stratocacher@0.0.8" instead of "stratocacher@^0.0.4".
Successfully bootstrapped 4 packages.
dougwade code/stratocacher ‹master*› » npm test

> @ test /Users/doug.wade/code/stratocacher
> lerna run test

Lerna run v1.1.1
Current version: 0.0.8
Version file location: /Users/doug.wade/code/stratocacher/VERSION
Packages location: /Users/doug.wade/code/stratocacher/packages
Run script failed
Errored while running npm script 'test' in packages.
npm ERR! Test failed.  See above for more details.
dougwade code/stratocacher ‹master*› » lerna run test                                                                                                                         1 ↵
Lerna v2.0.0-beta.5
Errored while running npm script 'test' in 'stratocacher'
Error: Command failed: /bin/sh -c npm run test
/usr/local/lib/node_modules/gulp/bin/gulp:13
  throw new Error("Missing Gulpfile");
  ^

Error: Missing Gulpfile
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp:13:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! stratocacher@0.0.8 test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stratocacher@0.0.8 test script 'gulp test'.
npm ERR! This is most likely a problem with the stratocacher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls stratocacher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/stratocacher/packages/stratocacher/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
Errored while running RunCommand.execute
Error: Command failed: /bin/sh -c npm run test
/usr/local/lib/node_modules/gulp/bin/gulp:13
  throw new Error("Missing Gulpfile");
  ^

Error: Missing Gulpfile
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp:13:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! stratocacher@0.0.8 test: `gulp test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stratocacher@0.0.8 test script 'gulp test'.
npm ERR! This is most likely a problem with the stratocacher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls stratocacher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/stratocacher/packages/stratocacher/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
dougwade code/stratocacher ‹master*› » ./node_modules/.bin/lerna run test                                                                                                     1 ↵
Lerna run v1.1.1
Current version: 0.0.8
Version file location: /Users/doug.wade/code/stratocacher/VERSION
Packages location: /Users/doug.wade/code/stratocacher/packages
Run script failed
Errored while running npm script 'test' in packages.
```

**Comment by doug-wade** [comment]
This one's on me -- I was trying to upgrade to the most recent gulp-cli, and downgraded my global gulp instead 🐑
